// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function JWTDecode(arg1:string):Promise<tools.JWTDecodeResult>;

export function JsonMinify(arg1:string):Promise<string>;

export function JsonPretty(arg1:string):Promise<string>;

export function JsonToYaml(arg1:string):Promise<string>;

export function MD5Hash(arg1:string):Promise<string>;

export function RSADecrypt(arg1:string,arg2:string):Promise<tools.RSADecryptResult>;

export function RSAEncrypt(arg1:string,arg2:string):Promise<tools.RSAEncryptResult>;

export function RSAGenerateKeyPair(arg1:number):Promise<tools.RSAKeyPair>;

export function SHA1Hash(arg1:string):Promise<string>;

export function SHA256Hash(arg1:string):Promise<string>;

export function TextDiff(arg1:string,arg2:string):Promise<tools.DiffResult>;

export function UrlDecode(arg1:string):Promise<string>;

export function UrlEncode(arg1:string):Promise<string>;

export function YamlPretty(arg1:string):Promise<string>;

export function YamlToJson(arg1:string):Promise<string>;
