// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['tools']['ToolService']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['tools']['ToolService']['Base64Encode'](arg1);
}

export function JWTDecode(arg1) {
  return window['go']['tools']['ToolService']['JWTDecode'](arg1);
}

export function JsonMinify(arg1) {
  return window['go']['tools']['ToolService']['JsonMinify'](arg1);
}

export function JsonPretty(arg1) {
  return window['go']['tools']['ToolService']['JsonPretty'](arg1);
}

export function JsonToYaml(arg1) {
  return window['go']['tools']['ToolService']['JsonToYaml'](arg1);
}

export function MD5Hash(arg1) {
  return window['go']['tools']['ToolService']['MD5Hash'](arg1);
}

export function RSADecrypt(arg1, arg2) {
  return window['go']['tools']['ToolService']['RSADecrypt'](arg1, arg2);
}

export function RSAEncrypt(arg1, arg2) {
  return window['go']['tools']['ToolService']['RSAEncrypt'](arg1, arg2);
}

export function RSAGenerateKeyPair(arg1) {
  return window['go']['tools']['ToolService']['RSAGenerateKeyPair'](arg1);
}

export function SHA1Hash(arg1) {
  return window['go']['tools']['ToolService']['SHA1Hash'](arg1);
}

export function SHA256Hash(arg1) {
  return window['go']['tools']['ToolService']['SHA256Hash'](arg1);
}

export function TextDiff(arg1, arg2) {
  return window['go']['tools']['ToolService']['TextDiff'](arg1, arg2);
}

export function UrlDecode(arg1) {
  return window['go']['tools']['ToolService']['UrlDecode'](arg1);
}

export function UrlEncode(arg1) {
  return window['go']['tools']['ToolService']['UrlEncode'](arg1);
}

export function YamlPretty(arg1) {
  return window['go']['tools']['ToolService']['YamlPretty'](arg1);
}

export function YamlToJson(arg1) {
  return window['go']['tools']['ToolService']['YamlToJson'](arg1);
}
